name: meteo_uyari
description: Live weather alerts from https://www.mgm.gov.tr
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  countries_world_map: ^1.1.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.0.0
  intl: ^0.19.0
  localstore: ^1.3.5
  supabase_flutter: ^2.0.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/alert_icons/
    - assets/screen_icons/
