name: meteo_uyari
description: Live weather alerts from https://www.mgm.gov.tr
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.9.3
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
