name: BuildTask

on:
  workflow_dispatch:
    inputs:
      build_type:
        type: choice
        description: "Build type for app"
        options:
          - alpha
          - beta
          - stable
        required: true
      publish:
        type: boolean
        description: "Whether publish to Google Play after build."
        default: false

jobs:
  build_android:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
          
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
 
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Running flutter tests
        run: flutter test
  
      - name: Start appbundle build
        run: flutter build appbundle --dart-define=buildType=${{ github.event.inputs.build_type }}
        
      - name: Start apk build
        run: flutter build apk --dart-define=buildType=${{ github.event.inputs.build_type }}

      - name: Uploading android packages
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

  release:
    env:
      isRelease: ${{ github.event.inputs.publish }}
    runs-on: ubuntu-latest
    needs: [build_android]
    steps:
      - uses: actions/checkout@v3

      - name: Downloading builds
        uses: actions/download-artifact@v3
        with: 
          name: builds

      - name: Releasing builds
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: ${{ env.isRelease == 'false' }}
          files: | 
            flutter-apk/app-release.apk
            bundle/release/app-release.aab


  google_play_publish:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
    - uses: actions/checkout@v2
    - name: Downloading builds
      uses: actions/download-artifact@v3
      with: 
         name: builds

    - name: Publish internal testing
      if:  ${{github.event.inputs.build_type == 'alpha'}}
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT }}
        packageName: com.alper.meteo_uyari
        releaseFiles: bundle/release/app-release.aab
        track: internal
        status: draft
        changesNotSentForReview: false

    - name: Publish closed test
      if: ${{github.event.inputs.build_type == 'beta'}}
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT }}
        packageName: com.alper.meteo_uyari
        releaseFiles: bundle/release/app-release.aab
        track: beta
  